module TNum
  Tnull = [
           [0,0,0,0,0,0],
           [0,nil,nil,nil,nil,0],
           [0,nil,nil,nil,nil,0],
           [0,nil,nil,nil,nil,0],
           [0,nil,nil,nil,nil,0],
           [0,0,0,0,0,0],
           [0,nil,nil,nil,nil,0],
           [0,nil,nil,nil,nil,0],
           [0,nil,nil,nil,nil,0],
           [0,nil,nil,nil,nil,0],
           [0,0,0,0,0,0]
          ]
  T = [
       [
        [0,1,1,1,1,0],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,0,0,0,0,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [0,1,1,1,1,0]
       ],
       [
        [0,0,0,0,0,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,0,0,0,0,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,0,0,0,0,1],
       ],
       [
        [0,1,1,1,1,0],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,1,1,1,1,0],
        [1,nil,nil,nil,nil,0],
        [1,nil,nil,nil,nil,0],
        [1,nil,nil,nil,nil,0],
        [1,nil,nil,nil,nil,0],
        [0,1,1,1,1,0]
       ],
       # T3 =
       [
        [0,1,1,1,1,0],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,1,1,1,1,0],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,1,1,1,1,0]
       ],
       # T4 =
       [
        [0,0,0,0,0,0],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [0,1,1,1,1,0],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,0,0,0,0,0],
       ],
       # T5 =
       [
        [0,1,1,1,1,0],
        [1,nil,nil,nil,nil,0],
        [1,nil,nil,nil,nil,0],
        [1,nil,nil,nil,nil,0],
        [1,nil,nil,nil,nil,0],
        [0,1,1,1,1,0],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,1,1,1,1,0]
       ],
       # T6 =
       [
        [0,1,1,1,1,0],
        [1,nil,nil,nil,nil,0],
        [1,nil,nil,nil,nil,0],
        [1,nil,nil,nil,nil,0],
        [1,nil,nil,nil,nil,0],
        [0,1,1,1,1,0],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [0,1,1,1,1,0]
       ],
       # T7 =
       [
        [0,1,1,1,1,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,0,0,0,0,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,0,0,0,0,1],
       ],
       # T8 =
       [
        [0,1,1,1,1,0],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [0,1,1,1,1,0],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [0,1,1,1,1,0]
       ],
       # T9 =
       [
        [0,1,1,1,1,0],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [1,nil,nil,nil,nil,1],
        [0,1,1,1,1,0],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,nil,nil,nil,nil,1],
        [0,1,1,1,1,0]
       ]
      ]
end
